name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          rm -rf .git
          git init
          git config --global init.defaultBranch main
          git add .
          git commit -m "deploy: fresh production build without binary history"
          
          git remote add hf https://siddiquRahman:$HF_TOKEN@huggingface.co/spaces/siddiquRahman/developer-portfolio
          git push --force hf main